{% set name = "ibm_db_sa" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7ebdbf29d34b23870b7d22e3c55aef9b4e90250e3fb163bd6dde670326d6a34f

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - libxml2-devel

  run:
    - python
    - setuptools
    - sqlalchemy

test:
  imports:
    - ibm_db_sa

about:
  home: https://pypi.org/project/ibm-db-sa/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python SQLAlchemy driver for DB2 (LUW, zOS, i5) and IDS

  description: |
    This extension is the implementation of Python Alchmey driver for sqlAlchemy.
    The extension supports DB2 (LUW, zOS, i5)
  doc_url: https://github.com/ibmdb/python-ibmdbsa/blob/master/README.md
  dev_url: https://github.com/ibmdb/python-ibmdbsa

extra:
  recipe-maintainers:
    - pavelzw
    - '0xbe7a'
    - windiana42
    - amukherjee28
