{% set name = "ibm_db_sa" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 21086bbab8161dddf650644f6743e42f530d48d505562e12a8a12138744211e0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - python
    - pip
    - setuptools
    - libxml2

  run:
    - python
    - setuptools
    - sqlalchemy

test:
  imports:
    - ibm_db_sa

about:
  home: https://pypi.org/project/ibm-db-sa/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python SQLAlchemy driver for DB2 (LUW, zOS, i5) and IDS

  description: |
    This extension is the implementation of Python Alchmey driver for sqlAlchemy.
    The extension supports DB2 (LUW, zOS, i5)
  doc_url: https://github.com/ibmdb/python-ibmdbsa/blob/master/README.md
  dev_url: https://github.com/ibmdb/python-ibmdbsa

extra:
  recipe-maintainers:
    - windiana42
    - amukherjee28
