{% set name = "ibm_db_sa" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2aa3f794abc8e702fd315cb34080107e746c9203033d507df17266cf0a3e3b65

build:
  number: 3
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - python
    - pip
    - setuptools
    - libxml2

  run:
    - python
    - setuptools
    - sqlalchemy

test:
  imports:
    - ibm_db_sa

about:
  home: https://pypi.org/project/ibm-db-sa/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python SQLAlchemy driver for DB2 (LUW, zOS, i5) and IDS

  description: |
    This extension is the implementation of Python Alchmey driver for sqlAlchemy.
    The extension supports DB2 (LUW, zOS, i5)
  doc_url: https://github.com/ibmdb/python-ibmdbsa/blob/master/README.md
  dev_url: https://github.com/ibmdb/python-ibmdbsa

extra:
  recipe-maintainers:
    - amukherjee28
